apiVersion: v1
kind: Secret
metadata:
  name: dayron-casas-secret
  namespace: dayron-casas
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://dayron:I42QPrwdDkOu6oiv@dayroncasas.2sg7aie.mongodb.net/?appName=dayroncasas&retryWrites=true&w=majority&tls=true"
  MONGODB_DATABASE: "dayroncasas"
  RAPIDAPI_KEY: "f660811b55msh8e0aa7e996567f4p1271cdjsnb88d51ac6281"
  RAPIDAPI_KEY_VALIDECT: "3ae0f32e7bmsh5f844a4658c7075p1466afjsn8f8e6c7b1a0f"
  SHAZAM_HOST: "shazam-api-free.p.rapidapi.com"
  SHAZAM_BASE_URL: "https://shazam-api-free.p.rapidapi.com"
  VALIDECT_HOST: "validect-email-verification-v1.p.rapidapi.com"
  VALIDECT_BASE_URL: "https://validect-email-verification-v1.p.rapidapi.com"
