apiVersion: v1
kind: Service
metadata:
  name: dayron-casas-service
  namespace: dayron-casas
spec:
  selector:
    app: dayron-casas
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
